database:
  uri: "postgresql://tiled:${POSTGRES_PASSWORD}@localhost:5432/auth"
  init_if_not_exists: true
authentication:
  providers:
    - provider: keycloak_oidc
      authenticator: tiled.authenticators:ProxiedOIDCAuthenticator
      args:
        audience: account
        client_id: tiled
        client_secret: tiled-secret
        device_flow_client_id: tiled-cli
        well_known_uri: "http://localhost:8081/realms/master/.well-known/openid-configuration"
        confirmation_message: "You have logged in with authn.diamond.ac.uk as {id}."
        redirect_on_success: "http://localhost:8407/ui/auth-callback"
        user_id_claim: fedid
        scopes_map:
          read: ["read:metadata", "read:data"]
          write: ["write:metadata", "write:data","create:node","register"]
        allow_ui_login: False
trees:
  - path: /
    tree: catalog
    args:
      uri: postgresql://tiled:${POSTGRES_PASSWORD}@localhost:5432/tiled_catalog
      writable_storage: postgresql://tiled:${POSTGRES_PASSWORD}@localhost:5432/data
      init_if_not_exists: true

streaming_cache:
  uri: redis://localhost:6379

access_control:
  access_policy: "tiled_policy.example_pdp:DiamondOpenPolicyAgentAuthorizationPolicy"
  args:
    authorization_provider: "http://localhost:8181/v1/data/diamond/policy/"
    token_audience: account
    empty_access_blob_public: true
