authentication:
  providers:
  - provider: keycloak_oidc
    authenticator: tiled.authenticators:ProxiedOIDCAuthenticator
    args:
      audience: tiled
      client_id: tiled
      client_secret: tiled-secret
      device_flow_client_id: tiled-cli
      well_known_uri: "http://localhost:8081/realms/master/.well-known/openid-configuration"
      confirmation_message: "You have logged in with Proxied OIDC as {id}."
      redirect_on_success: "http://127.0.0.1:8407/ui/auth-callback"
      user_id_claim: "fedid"

access_control:
  access_policy: "tiled_policy.dls:DiamondOpenPolicyAgentAuthorizationPolicy"
  args:
    authorization_provider: "http://localhost:8181/v1/data/diamond/policy/"
    token_audience: account
    empty_access_blob_public: true

trees:
  - path: /
    tree: catalog
    args:
      uri: "sqlite:///./catalog1.db"
      writable_storage: "./data1"
      # This creates the database if it does not exist. This is convenient, but in
      # a horizontally-scaled deployment, this can be a race condition and multiple
      # containers may simultaneously attempt to create the database.
      # If that is a problem, set this to false, and run:
      #
      # tiled catalog init URI
      #
      # separately.
      init_if_not_exists: true
streaming_cache:
  uri: redis://localhost:6379
